---
popup_light_color_temp_joy:
  template: "popup_light_brightness_joy"
  styles:
    grid:
      - grid-template-areas: "'header' 'content2' 'buttons' 'footer'"
      - grid-template-rows: "16vh 52vh 14vh 14vh;"
      - grid-template-columns: "1fr"
    custom_fields:
      content1:
        - display: "none"
      content2:
        - display: "block"
        - align-self: "center"
      content3:
        - display: "none"
  extra_styles: |
    @media (max-width: 2000px) {
      #container {
        grid-template-areas: "header" "content2" "buttons" "footer" !important;
        grid-template-rows: 16vh 52vh 14vh 14vh !important;
        grid-template-columns: 1fr !important;
      }
      #buttons {
        display: block !important;
        align-self: start !important;
      }
      #content1 {
        display: none;
      }
      #content3 {
        display: none;
      }
  custom_fields:
    buttons:
      card:
        type: "custom:button-card"
        template: "list_3_items"
        styles:
          card:
            - background: "none"
        custom_fields:
          item1:
            card:
              icon: "mdi:lightbulb-on"
              type: "custom:button-card"
              template:
                - "popup_button"
                - "popup_button_brightness"
              tap_action:
                action: "fire-dom-event"
                browser_mod:
                  service: browser_mod.popup
                  data:
                    hide_header: true
                    content:
                      type: "custom:button-card"
                      template: "popup_light_brightness_joy"
                      variables:
                        ulm_popup_light_entity: "[[[ return variables.ulm_popup_light_entity ]]]"
                        ulm_popup_light_wled_preset: "[[[ return variables.ulm_popup_light_wled_preset ]]]"  
          item2:
            card:
              icon: "mdi:sun-thermometer-outline"
              type: "custom:button-card"
              template:
                - "popup_button"
                - "popup_button_selected"
                - "popup_button_color_temp"
          item3:
            card:
              icon: "mdi:palette"
              type: "custom:button-card"
              template:
                - "popup_button"
                - "popup_button_color"
              tap_action:
                action: "fire-dom-event"
                browser_mod:
                  service: browser_mod.popup
                  data:
                    hide_header: true
                    content:
                      type: "custom:button-card"
                      template: "popup_light_color_joy"
                      variables:
                        ulm_popup_light_entity: "[[[ return variables.ulm_popup_light_entity ]]]"
                        ulm_popup_light_wled_preset: "[[[ return variables.ulm_popup_light_wled_preset ]]]"  